import { useEffect, useState } from 'react';
import { getUnitAssessment, saveUnitAssessment } from '../services/unitAssessmentService';
import './UnitAssessment.css';

export function UnitAssessment({ unitId, unitTitle, onClose }) {
  const [items, setItems] = useState([]); const [answers, setAnswers] = useState({}); const [isLoading, setIsLoading] = useState(true); const [result, setResult] = useState(null); const [error, setError] = useState('');
  useEffect(() => { getUnitAssessment(unitId).then(setItems).catch((err) => setError(err.message)).finally(() => setIsLoading(false)); }, [unitId]);
  if (isLoading) return <section className="unit-assessment"><p>Cargando evaluación...</p></section>;
  if (error) return <section className="unit-assessment"><button className="text-button" type="button" onClick={onClose}>← Volver</button><p role="alert">{error}</p></section>;
  if (!items.length) return <section className="unit-assessment"><button className="text-button" type="button" onClick={onClose}>← Volver</button><p>Aún no hay ejercicios suficientes para evaluar esta unidad.</p></section>;
  async function finish() { const score = Math.round((Object.values(answers).filter(Boolean).length / items.length) * 100); try { await saveUnitAssessment({ unitId, score, answers: items.map((item) => ({ exerciseId: item.id, correct: Boolean(answers[item.id]) })) }); setResult(score); } catch (err) { setError(err.message); } }
  return <section className="unit-assessment"><button className="text-button" type="button" onClick={onClose}>← Volver a la ruta</button><p className="eyebrow">Evaluación de dominio</p><h2>{unitTitle}</h2>{result === null ? <><p>Responde las preguntas y demuestra que puedes usar lo aprendido en esta unidad.</p><div className="assessment-items">{items.map((item, index) => <article key={item.id}><small>Pregunta {index + 1} · {item.lessonTitle}</small><h3>{item.prompt}</h3><div>{item.exercise_options.sort((a, b) => a.sort_order - b.sort_order).map((option) => <button type="button" key={option.id} className={answers[item.id] === option.is_correct ? 'assessment-option selected' : 'assessment-option'} onClick={() => setAnswers({ ...answers, [item.id]: option.is_correct })}>{option.option_text}</button>)}</div></article>)}</div><button className="primary-button" type="button" disabled={Object.keys(answers).length < items.length} onClick={finish}>Ver resultado</button></> : <div className="assessment-result"><strong>{result}%</strong><h3>{result >= 80 ? 'Unidad dominada' : 'Aún puedes reforzarla'}</h3><p>{result >= 80 ? 'Puedes avanzar con confianza y volver cuando quieras.' : 'Te recomendamos repetir las lecciones con más errores antes de intentarlo otra vez.'}</p><button className="primary-button" type="button" onClick={onClose}>Continuar</button></div>}</section>;
}
